corn/corn/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('myauth.urls')),
    path('directory/', include('directory.urls')),
    path('all_orders/', include('all_orders.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

corn/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (
    set_cookie_view,
    get_cookie_view,
    login_view,
    logout_view,
    AboutMeView,
    RegisterView,

)


app_name = 'myauth'
urlpatterns = [
    path('', LoginView.as_view(
        template_name='myauth/login.html',
        redirect_authenticated_user=True,
    ),
         name='login'),

    path('logout', logout_view, name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),
    path('cookie/get/', get_cookie_view, name='cookie_get'),
    path('cookie/set/', set_cookie_view, name='cookie_set'),
]

corn/templates/inc/footer.html
<footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <p class="mb-0">&copy; {% now "Y" %} Мой Django-проект. Все права защищены.</p>
                </div>
                <div class="col-md-6 text-md-end">
                    <p class="mb-0">Версия: 1.0.0</p>
                </div>
            </div>
        </div>
    </footer>

corn/templates/inc/nav_.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class="navbar-brand" href="{% url 'order_list' %}">
            <i class="bi bi-box-seam"></i> Zero
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_order' %}">
                        <i class="bi bi-list-ul"></i> Новый заказ
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pay_list' %}">
                        <i class="bi bi-box-seam"></i> ПКО
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'expense_order_list' %}">
                        <i class="bi bi-list-ul"></i> РКО
                    </a>
                </li>
            </ul>

            <div class="d-flex">
                {% if user.is_authenticated %}
                <div class="dropdown">
                    <button class="btn btn-outline-light dropdown-toggle" type="button" id="userMenu"
                            data-bs-toggle="dropdown">
                        <i class="bi bi-person-circle"></i> {{ user.username }}
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="{% url 'admin:index' %}">
                            <i class="bi bi-person"></i> Профиль
                        </a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'myauth:logout'%}">
                            <i class="bi bi-box-arrow-right"></i> Выйти
                        </a></li>
                    </ul>
                </div>
                {% else %}
                <a href="{% url 'myauth:login' %}" class="btn btn-outline-light me-2">
                    <i class="bi bi-box-arrow-in-right"></i> Войти
                </a>
                <a href="{% url 'myauth:register' %}" class="btn btn-light">
                    <i class="bi bi-person-plus"></i> Регистрация
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>